# Generated by Django 2.2.20 on 2021-05-07 11:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stud_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StProfile',
            new_name='StudentProfile',
        ),
    ]
